name: Auto Merge Main to Testing

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{secrets.ACTIONS_PAT}}

      - name: Configure Git
        run: |
          git config --global user.name 'SriramYagnaPriya'
          git config --global user.email 'sriramyagnapriya2005.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge main into testing
        run: |
          git checkout testing
          git merge main -X theirs --allow-unrelated-histories
          git push origin testing